name: fhir_dart
description: A Dart package that provides full support for all FHIR (Fast Healthcare Interoperability Resources) R4 resources in Dart, enabling parsing, manipulation, and serialization.
version: 0.1.5
repository: https://github.com/pistevo-decision/fhir_dart
issue_tracker: https://github.com/pistevo-decision/fhir_dart/issues
environment:
  sdk: ^3.5.4

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
