part of '../fhir_dart.dart';

abstract class FhirResource {
  factory FhirResource.fromJson(Map<String, dynamic> json) {
    switch (json['resourceType']) {
      case Account.resourceType:
        return Account.fromJson(json);
      case ActivityDefinition.resourceType:
        return ActivityDefinition.fromJson(json);
      case AdverseEvent.resourceType:
        return AdverseEvent.fromJson(json);
      case AllergyIntolerance.resourceType:
        return AllergyIntolerance.fromJson(json);
      case Appointment.resourceType:
        return Appointment.fromJson(json);
      case AppointmentResponse.resourceType:
        return AppointmentResponse.fromJson(json);
      case AuditEvent.resourceType:
        return AuditEvent.fromJson(json);
      case Basic.resourceType:
        return Basic.fromJson(json);
      case Binary.resourceType:
        return Binary.fromJson(json);
      case BiologicallyDerivedProduct.resourceType:
        return BiologicallyDerivedProduct.fromJson(json);
      case BodyStructure.resourceType:
        return BodyStructure.fromJson(json);
      case Bundle.resourceType:
        return Bundle.fromJson(json);
      case CapabilityStatement.resourceType:
        return CapabilityStatement.fromJson(json);
      case CarePlan.resourceType:
        return CarePlan.fromJson(json);
      case CareTeam.resourceType:
        return CareTeam.fromJson(json);
      case CatalogEntry.resourceType:
        return CatalogEntry.fromJson(json);
      case ChargeItem.resourceType:
        return ChargeItem.fromJson(json);
      case ChargeItemDefinition.resourceType:
        return ChargeItemDefinition.fromJson(json);
      case Claim.resourceType:
        return Claim.fromJson(json);
      case ClaimResponse.resourceType:
        return ClaimResponse.fromJson(json);
      case ClinicalImpression.resourceType:
        return ClinicalImpression.fromJson(json);
      case CodeSystem.resourceType:
        return CodeSystem.fromJson(json);
      case Communication.resourceType:
        return Communication.fromJson(json);
      case CommunicationRequest.resourceType:
        return CommunicationRequest.fromJson(json);
      case CompartmentDefinition.resourceType:
        return CompartmentDefinition.fromJson(json);
      case Composition.resourceType:
        return Composition.fromJson(json);
      case ConceptMap.resourceType:
        return ConceptMap.fromJson(json);
      case Condition.resourceType:
        return Condition.fromJson(json);
      case Consent.resourceType:
        return Consent.fromJson(json);
      case Contract.resourceType:
        return Contract.fromJson(json);
      case Coverage.resourceType:
        return Coverage.fromJson(json);
      case CoverageEligibilityRequest.resourceType:
        return CoverageEligibilityRequest.fromJson(json);
      case CoverageEligibilityResponse.resourceType:
        return CoverageEligibilityResponse.fromJson(json);
      case DetectedIssue.resourceType:
        return DetectedIssue.fromJson(json);
      case Device.resourceType:
        return Device.fromJson(json);
      case DeviceDefinition.resourceType:
        return DeviceDefinition.fromJson(json);
      case DeviceMetric.resourceType:
        return DeviceMetric.fromJson(json);
      case DeviceRequest.resourceType:
        return DeviceRequest.fromJson(json);
      case DeviceUseStatement.resourceType:
        return DeviceUseStatement.fromJson(json);
      case DiagnosticReport.resourceType:
        return DiagnosticReport.fromJson(json);
      case DocumentManifest.resourceType:
        return DocumentManifest.fromJson(json);
      case DocumentReference.resourceType:
        return DocumentReference.fromJson(json);
      case EffectEvidenceSynthesis.resourceType:
        return EffectEvidenceSynthesis.fromJson(json);
      case Encounter.resourceType:
        return Encounter.fromJson(json);
      case Endpoint.resourceType:
        return Endpoint.fromJson(json);
      case EnrollmentRequest.resourceType:
        return EnrollmentRequest.fromJson(json);
      case EnrollmentResponse.resourceType:
        return EnrollmentResponse.fromJson(json);
      case EpisodeOfCare.resourceType:
        return EpisodeOfCare.fromJson(json);
      case EventDefinition.resourceType:
        return EventDefinition.fromJson(json);
      case Evidence.resourceType:
        return Evidence.fromJson(json);
      case EvidenceVariable.resourceType:
        return EvidenceVariable.fromJson(json);
      case ExampleScenario.resourceType:
        return ExampleScenario.fromJson(json);
      case ExplanationOfBenefit.resourceType:
        return ExplanationOfBenefit.fromJson(json);
      case FamilyMemberHistory.resourceType:
        return FamilyMemberHistory.fromJson(json);
      case FhirList.resourceType:
        return FhirList.fromJson(json);
      case Flag.resourceType:
        return Flag.fromJson(json);
      case Goal.resourceType:
        return Goal.fromJson(json);
      case GraphDefinition.resourceType:
        return GraphDefinition.fromJson(json);
      case Group.resourceType:
        return Group.fromJson(json);
      case GuidanceResponse.resourceType:
        return GuidanceResponse.fromJson(json);
      case HealthcareService.resourceType:
        return HealthcareService.fromJson(json);
      case ImagingStudy.resourceType:
        return ImagingStudy.fromJson(json);
      case Immunization.resourceType:
        return Immunization.fromJson(json);
      case ImmunizationEvaluation.resourceType:
        return ImmunizationEvaluation.fromJson(json);
      case ImmunizationRecommendation.resourceType:
        return ImmunizationRecommendation.fromJson(json);
      case ImplementationGuide.resourceType:
        return ImplementationGuide.fromJson(json);
      case InsurancePlan.resourceType:
        return InsurancePlan.fromJson(json);
      case Invoice.resourceType:
        return Invoice.fromJson(json);
      case Library.resourceType:
        return Library.fromJson(json);
      case Linkage.resourceType:
        return Linkage.fromJson(json);
      case Location.resourceType:
        return Location.fromJson(json);
      case Measure.resourceType:
        return Measure.fromJson(json);
      case MeasureReport.resourceType:
        return MeasureReport.fromJson(json);
      case Media.resourceType:
        return Media.fromJson(json);
      case Medication.resourceType:
        return Medication.fromJson(json);
      case MedicationAdministration.resourceType:
        return MedicationAdministration.fromJson(json);
      case MedicationDispense.resourceType:
        return MedicationDispense.fromJson(json);
      case MedicationKnowledge.resourceType:
        return MedicationKnowledge.fromJson(json);
      case MedicationRequest.resourceType:
        return MedicationRequest.fromJson(json);
      case MedicationStatement.resourceType:
        return MedicationStatement.fromJson(json);
      case MedicinalProduct.resourceType:
        return MedicinalProduct.fromJson(json);
      case MedicinalProductAuthorization.resourceType:
        return MedicinalProductAuthorization.fromJson(json);
      case MedicinalProductContraindication.resourceType:
        return MedicinalProductContraindication.fromJson(json);
      case MedicinalProductIndication.resourceType:
        return MedicinalProductIndication.fromJson(json);
      case MedicinalProductIngredient.resourceType:
        return MedicinalProductIngredient.fromJson(json);
      case MedicinalProductInteraction.resourceType:
        return MedicinalProductInteraction.fromJson(json);
      case MedicinalProductManufactured.resourceType:
        return MedicinalProductManufactured.fromJson(json);
      case MedicinalProductPackaged.resourceType:
        return MedicinalProductPackaged.fromJson(json);
      case MedicinalProductPharmaceutical.resourceType:
        return MedicinalProductPharmaceutical.fromJson(json);
      case MedicinalProductUndesirableEffect.resourceType:
        return MedicinalProductUndesirableEffect.fromJson(json);
      case MessageDefinition.resourceType:
        return MessageDefinition.fromJson(json);
      case MessageHeader.resourceType:
        return MessageHeader.fromJson(json);
      case MolecularSequence.resourceType:
        return MolecularSequence.fromJson(json);
      case NamingSystem.resourceType:
        return NamingSystem.fromJson(json);
      case NutritionOrder.resourceType:
        return NutritionOrder.fromJson(json);
      case Observation.resourceType:
        return Observation.fromJson(json);
      case ObservationDefinition.resourceType:
        return ObservationDefinition.fromJson(json);
      case OperationDefinition.resourceType:
        return OperationDefinition.fromJson(json);
      case OperationOutcome.resourceType:
        return OperationOutcome.fromJson(json);
      case Organization.resourceType:
        return Organization.fromJson(json);
      case OrganizationAffiliation.resourceType:
        return OrganizationAffiliation.fromJson(json);
      case Parameters.resourceType:
        return Parameters.fromJson(json);
      case Patient.resourceType:
        return Patient.fromJson(json);
      case PaymentNotice.resourceType:
        return PaymentNotice.fromJson(json);
      case PaymentReconciliation.resourceType:
        return PaymentReconciliation.fromJson(json);
      case Person.resourceType:
        return Person.fromJson(json);
      case PlanDefinition.resourceType:
        return PlanDefinition.fromJson(json);
      case Practitioner.resourceType:
        return Practitioner.fromJson(json);
      case PractitionerRole.resourceType:
        return PractitionerRole.fromJson(json);
      case Procedure.resourceType:
        return Procedure.fromJson(json);
      case Provenance.resourceType:
        return Provenance.fromJson(json);
      case Questionnaire.resourceType:
        return Questionnaire.fromJson(json);
      case QuestionnaireResponse.resourceType:
        return QuestionnaireResponse.fromJson(json);
      case RelatedPerson.resourceType:
        return RelatedPerson.fromJson(json);
      case RequestGroup.resourceType:
        return RequestGroup.fromJson(json);
      case ResearchDefinition.resourceType:
        return ResearchDefinition.fromJson(json);
      case ResearchElementDefinition.resourceType:
        return ResearchElementDefinition.fromJson(json);
      case ResearchStudy.resourceType:
        return ResearchStudy.fromJson(json);
      case ResearchSubject.resourceType:
        return ResearchSubject.fromJson(json);
      case RiskAssessment.resourceType:
        return RiskAssessment.fromJson(json);
      case RiskEvidenceSynthesis.resourceType:
        return RiskEvidenceSynthesis.fromJson(json);
      case Schedule.resourceType:
        return Schedule.fromJson(json);
      case SearchParameter.resourceType:
        return SearchParameter.fromJson(json);
      case ServiceRequest.resourceType:
        return ServiceRequest.fromJson(json);
      case Slot.resourceType:
        return Slot.fromJson(json);
      case Specimen.resourceType:
        return Specimen.fromJson(json);
      case SpecimenDefinition.resourceType:
        return SpecimenDefinition.fromJson(json);
      case StructureDefinition.resourceType:
        return StructureDefinition.fromJson(json);
      case StructureMap.resourceType:
        return StructureMap.fromJson(json);
      case Subscription.resourceType:
        return Subscription.fromJson(json);
      case Substance.resourceType:
        return Substance.fromJson(json);
      case SubstanceNucleicAcid.resourceType:
        return SubstanceNucleicAcid.fromJson(json);
      case SubstancePolymer.resourceType:
        return SubstancePolymer.fromJson(json);
      case SubstanceProtein.resourceType:
        return SubstanceProtein.fromJson(json);
      case SubstanceReferenceInformation.resourceType:
        return SubstanceReferenceInformation.fromJson(json);
      case SubstanceSourceMaterial.resourceType:
        return SubstanceSourceMaterial.fromJson(json);
      case SubstanceSpecification.resourceType:
        return SubstanceSpecification.fromJson(json);
      case SupplyDelivery.resourceType:
        return SupplyDelivery.fromJson(json);
      case SupplyRequest.resourceType:
        return SupplyRequest.fromJson(json);
      case Task.resourceType:
        return Task.fromJson(json);
      case TerminologyCapabilities.resourceType:
        return TerminologyCapabilities.fromJson(json);
      case TestReport.resourceType:
        return TestReport.fromJson(json);
      case TestScript.resourceType:
        return TestScript.fromJson(json);
      case ValueSet.resourceType:
        return ValueSet.fromJson(json);
      case VerificationResult.resourceType:
        return VerificationResult.fromJson(json);
      case VisionPrescription.resourceType:
        return VisionPrescription.fromJson(json);
      default:
        throw Exception('Invalid resource type: ${json['resourceType']}');
    }
  }
  Map<String, dynamic> toJson();
}
