part of '../fhir_dart.dart';

abstract class FhirResource {
  factory FhirResource.fromJson(Map<String, dynamic> json) {
    switch (json['resourceType']) {
      case Account.fhirResourceType:
        return Account.fromJson(json);
      case ActivityDefinition.fhirResourceType:
        return ActivityDefinition.fromJson(json);
      case AdverseEvent.fhirResourceType:
        return AdverseEvent.fromJson(json);
      case AllergyIntolerance.fhirResourceType:
        return AllergyIntolerance.fromJson(json);
      case Appointment.fhirResourceType:
        return Appointment.fromJson(json);
      case AppointmentResponse.fhirResourceType:
        return AppointmentResponse.fromJson(json);
      case AuditEvent.fhirResourceType:
        return AuditEvent.fromJson(json);
      case Basic.fhirResourceType:
        return Basic.fromJson(json);
      case Binary.fhirResourceType:
        return Binary.fromJson(json);
      case BiologicallyDerivedProduct.fhirResourceType:
        return BiologicallyDerivedProduct.fromJson(json);
      case BodyStructure.fhirResourceType:
        return BodyStructure.fromJson(json);
      case Bundle.fhirResourceType:
        return Bundle.fromJson(json);
      case CapabilityStatement.fhirResourceType:
        return CapabilityStatement.fromJson(json);
      case CarePlan.fhirResourceType:
        return CarePlan.fromJson(json);
      case CareTeam.fhirResourceType:
        return CareTeam.fromJson(json);
      case CatalogEntry.fhirResourceType:
        return CatalogEntry.fromJson(json);
      case ChargeItem.fhirResourceType:
        return ChargeItem.fromJson(json);
      case ChargeItemDefinition.fhirResourceType:
        return ChargeItemDefinition.fromJson(json);
      case Claim.fhirResourceType:
        return Claim.fromJson(json);
      case ClaimResponse.fhirResourceType:
        return ClaimResponse.fromJson(json);
      case ClinicalImpression.fhirResourceType:
        return ClinicalImpression.fromJson(json);
      case CodeSystem.fhirResourceType:
        return CodeSystem.fromJson(json);
      case Communication.fhirResourceType:
        return Communication.fromJson(json);
      case CommunicationRequest.fhirResourceType:
        return CommunicationRequest.fromJson(json);
      case CompartmentDefinition.fhirResourceType:
        return CompartmentDefinition.fromJson(json);
      case Composition.fhirResourceType:
        return Composition.fromJson(json);
      case ConceptMap.fhirResourceType:
        return ConceptMap.fromJson(json);
      case Condition.fhirResourceType:
        return Condition.fromJson(json);
      case Consent.fhirResourceType:
        return Consent.fromJson(json);
      case Contract.fhirResourceType:
        return Contract.fromJson(json);
      case Coverage.fhirResourceType:
        return Coverage.fromJson(json);
      case CoverageEligibilityRequest.fhirResourceType:
        return CoverageEligibilityRequest.fromJson(json);
      case CoverageEligibilityResponse.fhirResourceType:
        return CoverageEligibilityResponse.fromJson(json);
      case DetectedIssue.fhirResourceType:
        return DetectedIssue.fromJson(json);
      case Device.fhirResourceType:
        return Device.fromJson(json);
      case DeviceDefinition.fhirResourceType:
        return DeviceDefinition.fromJson(json);
      case DeviceMetric.fhirResourceType:
        return DeviceMetric.fromJson(json);
      case DeviceRequest.fhirResourceType:
        return DeviceRequest.fromJson(json);
      case DeviceUseStatement.fhirResourceType:
        return DeviceUseStatement.fromJson(json);
      case DiagnosticReport.fhirResourceType:
        return DiagnosticReport.fromJson(json);
      case DocumentManifest.fhirResourceType:
        return DocumentManifest.fromJson(json);
      case DocumentReference.fhirResourceType:
        return DocumentReference.fromJson(json);
      case EffectEvidenceSynthesis.fhirResourceType:
        return EffectEvidenceSynthesis.fromJson(json);
      case Encounter.fhirResourceType:
        return Encounter.fromJson(json);
      case Endpoint.fhirResourceType:
        return Endpoint.fromJson(json);
      case EnrollmentRequest.fhirResourceType:
        return EnrollmentRequest.fromJson(json);
      case EnrollmentResponse.fhirResourceType:
        return EnrollmentResponse.fromJson(json);
      case EpisodeOfCare.fhirResourceType:
        return EpisodeOfCare.fromJson(json);
      case EventDefinition.fhirResourceType:
        return EventDefinition.fromJson(json);
      case Evidence.fhirResourceType:
        return Evidence.fromJson(json);
      case EvidenceVariable.fhirResourceType:
        return EvidenceVariable.fromJson(json);
      case ExampleScenario.fhirResourceType:
        return ExampleScenario.fromJson(json);
      case ExplanationOfBenefit.fhirResourceType:
        return ExplanationOfBenefit.fromJson(json);
      case FamilyMemberHistory.fhirResourceType:
        return FamilyMemberHistory.fromJson(json);
      case FhirList.fhirResourceType:
        return FhirList.fromJson(json);
      case Flag.fhirResourceType:
        return Flag.fromJson(json);
      case Goal.fhirResourceType:
        return Goal.fromJson(json);
      case GraphDefinition.fhirResourceType:
        return GraphDefinition.fromJson(json);
      case Group.fhirResourceType:
        return Group.fromJson(json);
      case GuidanceResponse.fhirResourceType:
        return GuidanceResponse.fromJson(json);
      case HealthcareService.fhirResourceType:
        return HealthcareService.fromJson(json);
      case ImagingStudy.fhirResourceType:
        return ImagingStudy.fromJson(json);
      case Immunization.fhirResourceType:
        return Immunization.fromJson(json);
      case ImmunizationEvaluation.fhirResourceType:
        return ImmunizationEvaluation.fromJson(json);
      case ImmunizationRecommendation.fhirResourceType:
        return ImmunizationRecommendation.fromJson(json);
      case ImplementationGuide.fhirResourceType:
        return ImplementationGuide.fromJson(json);
      case InsurancePlan.fhirResourceType:
        return InsurancePlan.fromJson(json);
      case Invoice.fhirResourceType:
        return Invoice.fromJson(json);
      case Library.fhirResourceType:
        return Library.fromJson(json);
      case Linkage.fhirResourceType:
        return Linkage.fromJson(json);
      case Location.fhirResourceType:
        return Location.fromJson(json);
      case Measure.fhirResourceType:
        return Measure.fromJson(json);
      case MeasureReport.fhirResourceType:
        return MeasureReport.fromJson(json);
      case Media.fhirResourceType:
        return Media.fromJson(json);
      case Medication.fhirResourceType:
        return Medication.fromJson(json);
      case MedicationAdministration.fhirResourceType:
        return MedicationAdministration.fromJson(json);
      case MedicationDispense.fhirResourceType:
        return MedicationDispense.fromJson(json);
      case MedicationKnowledge.fhirResourceType:
        return MedicationKnowledge.fromJson(json);
      case MedicationRequest.fhirResourceType:
        return MedicationRequest.fromJson(json);
      case MedicationStatement.fhirResourceType:
        return MedicationStatement.fromJson(json);
      case MedicinalProduct.fhirResourceType:
        return MedicinalProduct.fromJson(json);
      case MedicinalProductAuthorization.fhirResourceType:
        return MedicinalProductAuthorization.fromJson(json);
      case MedicinalProductContraindication.fhirResourceType:
        return MedicinalProductContraindication.fromJson(json);
      case MedicinalProductIndication.fhirResourceType:
        return MedicinalProductIndication.fromJson(json);
      case MedicinalProductIngredient.fhirResourceType:
        return MedicinalProductIngredient.fromJson(json);
      case MedicinalProductInteraction.fhirResourceType:
        return MedicinalProductInteraction.fromJson(json);
      case MedicinalProductManufactured.fhirResourceType:
        return MedicinalProductManufactured.fromJson(json);
      case MedicinalProductPackaged.fhirResourceType:
        return MedicinalProductPackaged.fromJson(json);
      case MedicinalProductPharmaceutical.fhirResourceType:
        return MedicinalProductPharmaceutical.fromJson(json);
      case MedicinalProductUndesirableEffect.fhirResourceType:
        return MedicinalProductUndesirableEffect.fromJson(json);
      case MessageDefinition.fhirResourceType:
        return MessageDefinition.fromJson(json);
      case MessageHeader.fhirResourceType:
        return MessageHeader.fromJson(json);
      case MolecularSequence.fhirResourceType:
        return MolecularSequence.fromJson(json);
      case NamingSystem.fhirResourceType:
        return NamingSystem.fromJson(json);
      case NutritionOrder.fhirResourceType:
        return NutritionOrder.fromJson(json);
      case Observation.fhirResourceType:
        return Observation.fromJson(json);
      case ObservationDefinition.fhirResourceType:
        return ObservationDefinition.fromJson(json);
      case OperationDefinition.fhirResourceType:
        return OperationDefinition.fromJson(json);
      case OperationOutcome.fhirResourceType:
        return OperationOutcome.fromJson(json);
      case Organization.fhirResourceType:
        return Organization.fromJson(json);
      case OrganizationAffiliation.fhirResourceType:
        return OrganizationAffiliation.fromJson(json);
      case Parameters.fhirResourceType:
        return Parameters.fromJson(json);
      case Patient.fhirResourceType:
        return Patient.fromJson(json);
      case PaymentNotice.fhirResourceType:
        return PaymentNotice.fromJson(json);
      case PaymentReconciliation.fhirResourceType:
        return PaymentReconciliation.fromJson(json);
      case Person.fhirResourceType:
        return Person.fromJson(json);
      case PlanDefinition.fhirResourceType:
        return PlanDefinition.fromJson(json);
      case Practitioner.fhirResourceType:
        return Practitioner.fromJson(json);
      case PractitionerRole.fhirResourceType:
        return PractitionerRole.fromJson(json);
      case Procedure.fhirResourceType:
        return Procedure.fromJson(json);
      case Provenance.fhirResourceType:
        return Provenance.fromJson(json);
      case Questionnaire.fhirResourceType:
        return Questionnaire.fromJson(json);
      case QuestionnaireResponse.fhirResourceType:
        return QuestionnaireResponse.fromJson(json);
      case RelatedPerson.fhirResourceType:
        return RelatedPerson.fromJson(json);
      case RequestGroup.fhirResourceType:
        return RequestGroup.fromJson(json);
      case ResearchDefinition.fhirResourceType:
        return ResearchDefinition.fromJson(json);
      case ResearchElementDefinition.fhirResourceType:
        return ResearchElementDefinition.fromJson(json);
      case ResearchStudy.fhirResourceType:
        return ResearchStudy.fromJson(json);
      case ResearchSubject.fhirResourceType:
        return ResearchSubject.fromJson(json);
      case RiskAssessment.fhirResourceType:
        return RiskAssessment.fromJson(json);
      case RiskEvidenceSynthesis.fhirResourceType:
        return RiskEvidenceSynthesis.fromJson(json);
      case Schedule.fhirResourceType:
        return Schedule.fromJson(json);
      case SearchParameter.fhirResourceType:
        return SearchParameter.fromJson(json);
      case ServiceRequest.fhirResourceType:
        return ServiceRequest.fromJson(json);
      case Slot.fhirResourceType:
        return Slot.fromJson(json);
      case Specimen.fhirResourceType:
        return Specimen.fromJson(json);
      case SpecimenDefinition.fhirResourceType:
        return SpecimenDefinition.fromJson(json);
      case StructureDefinition.fhirResourceType:
        return StructureDefinition.fromJson(json);
      case StructureMap.fhirResourceType:
        return StructureMap.fromJson(json);
      case Subscription.fhirResourceType:
        return Subscription.fromJson(json);
      case Substance.fhirResourceType:
        return Substance.fromJson(json);
      case SubstanceNucleicAcid.fhirResourceType:
        return SubstanceNucleicAcid.fromJson(json);
      case SubstancePolymer.fhirResourceType:
        return SubstancePolymer.fromJson(json);
      case SubstanceProtein.fhirResourceType:
        return SubstanceProtein.fromJson(json);
      case SubstanceReferenceInformation.fhirResourceType:
        return SubstanceReferenceInformation.fromJson(json);
      case SubstanceSourceMaterial.fhirResourceType:
        return SubstanceSourceMaterial.fromJson(json);
      case SubstanceSpecification.fhirResourceType:
        return SubstanceSpecification.fromJson(json);
      case SupplyDelivery.fhirResourceType:
        return SupplyDelivery.fromJson(json);
      case SupplyRequest.fhirResourceType:
        return SupplyRequest.fromJson(json);
      case Task.fhirResourceType:
        return Task.fromJson(json);
      case TerminologyCapabilities.fhirResourceType:
        return TerminologyCapabilities.fromJson(json);
      case TestReport.fhirResourceType:
        return TestReport.fromJson(json);
      case TestScript.fhirResourceType:
        return TestScript.fromJson(json);
      case ValueSet.fhirResourceType:
        return ValueSet.fromJson(json);
      case VerificationResult.fhirResourceType:
        return VerificationResult.fromJson(json);
      case VisionPrescription.fhirResourceType:
        return VisionPrescription.fromJson(json);
      default:
        throw Exception('Invalid resource type: ${json['resourceType']}');
    }
  }
  Map<String, dynamic> toJson();
}
